name:                todo-cli
version:             0.1.0.0
github:              "WJVincent/learn_haskell/todo_cli"
license:             BSD3
author:              "William Vincent"
maintainer:          "william@william-vincent.dev"
copyright:           "2021 William Vincent"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/WJVincent/learn_haskell/todo-cli#readme>

dependencies:
- base >= 4.7 && < 5
- dotenv
- open-browser

library:
  source-dirs: src

executables:
  todo-cli-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - todo-cli

tests:
  todo-cli-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - todo-cli
